### ISSUE TITLE
Implement a timer

### ISSUE THREAD

**Issue by willyandan** [willyandan/quickdraw.js#3]
# Description 
Implements a timer that starts when the game start and when its finish get the image on the board(#2)
## Prerequisites
- #2

## Todo
- [ ] Show the timer 
- [ ] Start the timer
- [ ] Get the image when the timer is over
